### PR TITLE
Hanging PR for prototyping.

### PR DESCRIPTION
**Pull request by ModestMC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by smithsp** [comment]
@conda-forge-admin, please rerender

**Comment by smithsp** [comment]
@ModestMC Thanks for opening this, to get testing of OSX back.  When you change a build option, you have to rerender to get all of the settings aligned across the build system.

**Comment by ModestMC** [comment]
Thanks @smithsp, I was very confused when I modified the options only to have the build tests remain unchanged.

**Comment by ModestMC** [comment]
Closing this as stale, I expect MDSplus to have updated their build process by the time I anticipate using this again.

**Pull request closed without merging**
