### PR TITLE
Bump version to 7.96.17

### PR DESCRIPTION
**Pull request by smithsp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by smithsp** [comment]
@conda-forge-admin, please rerender

**Comment by smithsp** [comment]
@kalling This is failing due to a change in the build or packaging procedures of MDS+, where a previous set of patches I had prepared are no longer appropriate.  Any help is appreciated.

**Comment by kalling** [comment]
@smithsp I'll take a look.

**Comment by smithsp** [comment]
Superceded by #35

**Pull request closed without merging**
